### ISSUE TITLE
Playlist finnished

### ISSUE THREAD

**Issue by Boniewow** [rishabh3354/TUBE2GO#1]
After i downloaded the playlist the popup window showing what downloaded cant close. the whole app not responding after. linux mint cinnamon latest.

**Comment by rishabh3354** [comment]
Hi Boniewow
Thanks for reporting the issue, let me replicate the issue and let you know if there is an active issue with it

**Comment by rishabh3354** [comment]
Thanks for reporting. it is now fixed in new version of the app. i am closing this issue for now.
